# mongo e node
version: '3.1'
services:
  mongo:
    image: mongo:7.0-rc-jammy
    container_name: manager-tasks-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
  api:
    container_name: manager-tasks-api
    user: node
    image: node:16
    restart: always
    ports:
      - 3001:3001
      - 9229:9229
    environment:
      - DB_URI=${DB_URI}
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: bash
    # As duas opções abaixo correspondem ao -it
    tty: true # -t
    stdin_open: true #-i
    depends_on:
      - mongo
